DROP DATABASE IF EXISTS FoodChoice;

CREATE DATABASE FoodChoice CHARACTER SET 'utf8';

USE FoodChoice;

CREATE TABLE IF NOT EXISTS `Substitute` (
  `Substitute_ID` SMALLINT UNSIGNED  NOT NULL AUTO_INCREMENT,
  `Users_ID` TINYINT UNSIGNED,
  `Product_ID` SMALLINT UNSIGNED,
  `Date` DATETIME,
  `Note` TEXT,
  KEY `PK, FK` (`Substitute_ID`),
  KEY `FK` (`Users_ID`, `Product_ID`)
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `Product` (
  `ID` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(150),
  `Code` BIGINT UNSIGNED,
  `Brand` VARCHAR(100),
  `Nutrition_grade` CHAR(1),
  `Energy_100g` SMALLINT UNSIGNED,
  `URL` VARCHAR(255),
  PRIMARY KEY (`ID`)
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `Store` (
  `ID` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50),
  PRIMARY KEY (`ID`)
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `CategoryProduct` (
  `Product_ID` TINYINT UNSIGNED NOT NULL,
  `Category_ID` SMALLINT UNSIGNED NOT NULL,
  KEY `PK, FK` (`Product_ID`, `Category_ID`)
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `ProductLocation` (
  `Product_ID` SMALLINT UNSIGNED NOT NULL,
  `City_ID` SMALLINT UNSIGNED NOT NULL,
  `Store_ID` SMALLINT UNSIGNED NOT NULL,
  KEY `PK, FK` (`Product_ID`, `City_ID`, `Store_ID`)
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `City` (
  `ID` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50),
  `Zip_code` SMALLINT UNSIGNED,
  PRIMARY KEY (`ID`)
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `Category` (
  `ID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50),
  PRIMARY KEY (`ID`)
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `Users` (
  `ID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(15),
  `Password` VARCHAR(15),
  PRIMARY KEY (`ID`)
)
ENGINE=INNODB;